config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :restaurants, except: %i[edit update] do
    resources :reviews, only: %i[new create]
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5).to_a }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.delete
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_restaurant.html.erb
<h3><%= link_to "#{restaurant.name}", "restaurants/#{restaurant.id}", class: "btn btn-primary" %></h3>
<p><%= restaurant.address %></p>
<p><%= restaurant.category %></p>
<hr>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%=link_to "Add a new restaurant!", "restaurants/new", class: "btn btn-primary"%>
<hr>
<div id="restaurants">
  <% @restaurants.each do |restaurant|%>
    <%= render restaurant%>
  <%end%>

app/views/restaurants/new.html.erb
<h1>Create a new Restaurant</h1>
<%= simple_form_for(@restaurant) do |f|%>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit class: "btn btn-primary"%>
<%end%>

app/views/restaurants/show.html.erb
<h1><%= "#{@restaurant.name}"%></h1>
<hr>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<%= link_to "Write a Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary"%>
<br>
<br>
<%= link_to "Delete",
  restaurant_path(@restaurant), class: "btn btn-primary",
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<hr>

<p><strong>Reviews</strong></p>
<ol>
  <% @restaurant.reviews.each do |review |%>
    <li class="list-group_item"><%= review.content %> Rating: <%= review.rating %></li>
  <% end %>
</ol>

<hr>

app/views/reviews/new.html.erb
<h1>Create Review for <%="#{@restaurant.name}"%></h1>
<%= simple_form_for [@restaurant, @review] do |f|%>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit class: "btn btn-primary"%>
<%end%>